[pkgs]
apt = ["gcc", "python3", "python3-venv", "python3-dev"]

[commands]
install = "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[phases.start]
cmd = "python bot estrutura botoes.py"  # Substitua pelo nome real do seu arquivo principal

